fix: headway and no-data sections take up 1 row when sharing with another section
mbta/screens pull request #1699
Opened 2023-04-12 13:22 UTC by jzimbel-mbta

**Asana task**: [headway_section and no_data_section should only take up one line](https://www.notion.so/mbta-downtown-crossing/headway_section-and-no_data_section-should-only-take-up-one-line-a1d8471b90f14df8bc1a30b28d6b2386?pvs=4)

![headway-section](https://user-images.githubusercontent.com/63608771/231285984-9744aad5-5973-4fcd-9796-23f2a504d014.png)
Headway section, on departures configured with two sections

![no-data-section](https://user-images.githubusercontent.com/63608771/231285999-c3d415a1-f844-484d-bcbb-0e9adcc27870.png)
No-data section, on departures configured with two sections

---

![headway-section-single-section-departures](https://user-images.githubusercontent.com/63608771/231470027-7c59158a-d69e-4f6a-9dc2-c9781b6f64cd.png)
Headway section, on departures configured with one section

![no-data-section-single-section-departures](https://user-images.githubusercontent.com/63608771/231470118-63cbcd00-0590-42d6-8353-df601ec1a06a.png)
No-data section, on departures configured with one section

- [ ] Tests added?

2023-04-18 20:08 UTC, hannahpurcell requested changes
The merge seems to have affected the fix

![Screenshot 2023-04-18 at 4 06 35 PM](https://user-images.githubusercontent.com/69368883/232893322-fea2009c-9105-41e6-935e-121bff78ab73.png)

2023-04-18 20:33 UTC, jzimbel-mbta commented
😩

2023-04-18 20:57 UTC, jzimbel-mbta commented
Should be good now! I gave the selectors increased specificity so I could specify height calculation for those particular cases.

My previous change just gave all sections variable height based on the total height of their contents, but based on changes on master since then, it looks like we need to fix the height at 416px for normal sections that share space with a second section.

2023-04-19 12:32 UTC, hannahpurcell approved these changes
One improvement. Otherwise, should be golden!

2023-04-19 12:32 UTC, hannahpurcell commented on assets/css/v2/dup/departures/no_data_section.scss
Ooo there's a general "comment on file" button now!

There's one extremely unlikely but also easy-to-resolve case where there is an alert AND there's a 
"data unavailable" situation.

At the bottom of this file:
```
.body-split__main-content-reduced .no-data-section {
  height: 208px;
}
```
Before:
![Screenshot 2023-04-19 at 8 23 46 AM](https://user-images.githubusercontent.com/69368883/233075551-157951ef-3024-43a7-af9c-046430568173.png)

After:
![Screenshot 2023-04-19 at 8 29 07 AM](https://user-images.githubusercontent.com/69368883/233075602-1b8489b2-e6f4-419f-aaf7-ce82a21f0dea.png)
![Screenshot 2023-04-19 at 8 29 35 AM](https://user-images.githubusercontent.com/69368883/233075629-eb4775b0-29e1-44e2-81bf-cdcfecfb8baa.png)

2023-04-19 14:31 UTC, merged