feat: Implement WidgetInstance.slot_names/1 for Alert widget
mbta/screens pull request #910
Opened 2021-06-29 13:19 UTC by jzimbel-mbta

**Asana task**: [determine widget slot name](https://app.asana.com/0/1185117109217413/1200354915858977/f)

Possibly helpful explanation of the big `reduce_while` inside `informs_all_active_routes_at_home_stop/1`: It starts with the set of routes that are actively serving the home stop on the current day as the accumulator. It looks at each informed entity one at a time, and removes any route IDs from the set.

If the set is empty after checking through all the informed entities, then the alert informs all active routes serving the home stop. If not, it does not inform all of them.

Note: I also updated `priority/1` to depend on `slot_names/1`. If `slot_names/1` returns `[:full_screen]`, then `priority/1` returns `[1]` in order to have the alert be placed before other widgets that might preclude it from getting the full-screen slot.

- [ ] Needs version bump?

2021-06-29 18:45 UTC, handorff requested changes
One small thing, otherwise looks good!

2021-06-29 18:45 UTC, handorff commented on lib/screens/v2/widget_instance/alert.ex
> +      [:medium_left, :medium_right]
I think `bus_eink_v2` just has `:medium_flex`.

2021-06-29 18:47 UTC, jzimbel-mbta commented on lib/screens/v2/widget_instance/alert.ex
> +      [:medium_left, :medium_right]
Good catch, thanks!

2021-06-30 20:05 UTC, handorff approved these changes
Thanks!

2021-06-30 20:06 UTC, merged